events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://app_b:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 81;

        location / {
            proxy_pass http://app_c:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
